#!/bin/ksh
#################################################################################################
## bld_lpid - script to build the .ri file and a template of the vtlscreens file used by       ##
##            the launcher application                                                         ##
##                                                                                             ##
##                                                                                             ##
##                                                                                             ##
##                                                     Author Stephen Woods ECS,Inc            ##
#################################################################################################
#local=`echo $DSSC_REL | awk ' {print substr($1,3,4) substr($1,8,1)}'`
#set -x
#rm file1
#rm Facility_Info*
##                                                                                             ##
##     House Keeping                                                                           ##
##                                                                                             ##
rm *.ri
rm file1
rm file2
echo $PATH >> Facility_Info.A
ft=1
fn=0
si=0
fa=0
kaps=1
kai=1
##                                                                                             ##
##                 Get the Site id and Local id                                                ##
##                                                                                             ##
while test "$ft" -gt "0"
do 
  clear
  echo " "
  echo " Please enter the Site Identifier that will be used or blank  when complete"
# echo $si
  read site 
  asite[$si]=$site
  usite=`echo $site | tr [:lower:] [:upper:]`
  ausite[$si]=$usite
  site=$usite
  rpd="    "
  dpd="    "
  rm Facility_Info*
  if test ${#site} -ge 1 
  then 
        mi=`expr $si + 1`
        ai=$kai
        aps=$kaps  
        #clear
        echo " "
	echo " Please enter the Local Identifier (eg. wh0 no0 ) that will be used"
	read slcl
        locl=`echo $DSSC_REL | awk ' {print substr($1,3,4) substr($1,8,1)}'`
        lcl=$locl$slcl
        plcl=`echo $lcl | awk '{print substr($1,6,3)}'`
	echo "please wait"
        while test "$fn" -lt 1
        do
	  fnam=$site"_"$lcl".ri"
	  rnam=$site"_"$lcl".run" 
	  dnam=$site"_"$lcl".vtlscreens"	
          fn=5
        done 
##                                                                                             ##
##           Get only Channel A information from facility info                                 ##
##                                                                                             ##
        if [ -d "/dssc/xmount/csrd/$lcl" ];   
            then 
             echo ""
            else 
             echo  "Release "$lcl " is not found, please try again"
             exit
        fi
	vtl_facility_info -l $lcl no_vi
        ch="A"
       `cat $HOME/Facility_Info.out | awk -v ch=$ch '{if ($8 == ch) print $0}' >>  Facility_Info.A`
##                                                                                             ##
##  Build the header information for each site in the ri file and vtlscreens template          ##
##                                                                                             ##
        lclnam="Facility_Info.A"
	if test "$mi" = 1
	then
		echo "#################     RI file was built by bld_lpid ######################################" >> file1
		echo "############     VTLSCREENS file was built by bld_lpid    ################################" >> file2
	fi
	echo "############" >> file1
	echo "# Optional Global Vars - if used, need both start date AND start time to be valid " >> file1
	echo "############" >> file1
	echo "#STARTDATE=YYYY/MM/DD" >> file1
	echo "#STARTTIME=HH:MM:SS" >> file1
	echo "############" >> file1
	echo "# Facility "$mi >> file1
	echo "############" >> file1
	echo "FAC="$usite":A" >> file1
	echo "LOCAL="$plcl >> file1
	echo "OPSIM="$si >> file1
	echo "HARNESS=1" >> file1
	echo "MODE=active" >> file1
	echo "# CPP - Conflict Probe" >> file1
        cpps=`cat $lclnam | grep -i CP01 |awk -v sc=CP01 -v ct=$ct '{if ($3==sc) print $1}'`
	echo "LPID="$cpps" APPS=CPB:TPM:FMS:CDP:TAI" >> file1
	echo "# FDP - Flight Data" >> file1
        cpps=`cat $lclnam | grep -i FDP1 |awk -v sc=FDP1 -v ct=$ct '{if ($3==sc) print $1}'`
	echo "LPID="$cpps" APPS=AIM:FDM:FMA:FMS:IFB:IA2:IA1:FPM:TJM:TKM:FDD:IFS" >> file1
	echo "# SDP - Surveillance Data" >> file1
        cpps=`cat $lclnam | grep -i SDP1 |awk -v sc=SDP1 -v ct=$ct '{if ($3==sc) print $1}'`
	echo "LPID="$cpps" APPS=SAe:TKS" >> file1
	echo "# SYNC - Sync Processor (No channel sync apps! Used normally)" >> file1
        cpps=`cat $lclnam | grep -i SYN1 |awk -v sc=SYN1 -v ct=$ct '{if ($3==sc) print $1}'`
	echo "LPID="$cpps" APPS=SET:STR" >> file1
	echo "# GIPWX - General Information Processing, WX processor" >> file1 
        cpps=`cat $lclnam | grep -i WXG1 |awk -v sc=WXG1 -v ct=$ct '{if ($3==sc) print $1}'`
	echo "LPID="$cpps" APPS=WXP:GIe" >> file1
##                                                                                             ##
##   First site gets an SSRV                                                                    ##
##                                                                                             ##
	if test "$mi" = 1
	then
		echo "# MCP with SSRV and MCWS required applications" >> file1
                cpps=`cat $lclnam | grep -i MC01 |awk -v sc=MC01 -v ct=$ct '{if ($3==sc) print $1}'`
		echo "LPID="$cpps" APPS=BGS:MnC:ANP:SDA:MDA:GMS:IPF:SSRV:SWI:LGSM:FIS" >> file1
        else
		echo "# MCP without SSRV and MCWS required applications" >> file1
		cpps=`cat $lclnam | grep -i MC01 |awk -v sc=MC01 -v ct=$ct '{if ($3==sc) print $1}'`
                echo "LPID="$cpp" APPS=BGS:MnC:ANP:SDA:MDA:GMS:IPF:SWI:LGSM:FIS" >> file1
	fi
	echo "#MCWS" >> file1
        cpps=`cat $lclnam | grep -i MCWS |awk -v sc=MCWS -v ct=$ct '{if ($2==sc) print $1}'`
        cppt=`echo $cpps | awk '{print substr($1,1,3)}'` 
	echo "LPID="$cppt" DISP=MCWS_"$mi" APPS=MCG:CMI" >> file1
	echo "export MCWS_"$mi"=10.141.1.xx:y" >> file2
##                                                                                             ##
##  Get the sector number and buils the d/da and r pos ri and vtlscreens lines                 ##
##                                                                                             ##
        lclnam="Facility_Info.A"
	ct=$ft
        while test "$ct" -gt 0
        do
#		clear
		echo "please enter Sector Number or blank when complete "
        	read a
        	if test ${#a} -ge 1 
		then
##                                                                                             ##
##  Make sure the sector is valid                                                             ##
##                                                                                             ##
		   schk=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print $2}'`
		     while test "$schk" = ""
				do
                                   clear
                                   echo " "
                                   echo "#################    ERROR     ######################################"
                                   echo " "
                                   echo " Vaild Sectors Are:"
                                   echo " "
                                   cat $lclnam | grep -i dpd | awk '{printf " " $5}'
                                   echo " "
                                   echo " "
				   echo "Sector Number not found, please enter Sector Number or cntrl-c to exit"
				   read a
				   schk=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print $2}'`
				done
			dachk="DASNT"
			dchk=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print $2}'`
                        if test "$dchk" = "DASNT"
                        then
				echo "## Sector "$a " DASNT" >> file1
				echo "## Sector "$a " DASNT" >> file2
                    		dpd=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct -v aps=$aps '{if ($5==sc) print "LPID="$1" DISP=DVu_"ct":APS_"aps" APPS=DVu:CMI"}'`
				dspd=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print "export DVu_"ct"=10.141.1.xx:y"}'`
				aspd=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$aps '{if ($5==sc) print "export APS_"ct"=10.141.1.xx:y"}'`
 				echo $aspd >> file2
			else
				echo "## Sector "$a " DATA" >> file1
				echo "## Sector "$a " DATA" >> file2
				dpd=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print "LPID="$1" DISP=DVu_"ct" APPS=DVu:CMI"}'`
				dspd=`cat $lclnam | grep -i dpd |awk -v sc=$a -v ct=$ct '{if ($5==sc) print "export DVu_"ct"=10.141.1.xx:y"}'`
			fi
			rpd=`cat $lclnam | grep -i radar |awk -v sc=$a -v ct=$ct '{if ($5==sc) print "LPID="$1" DISP=RPD_"ct" APPS=RPD:CMI"}'`
			rspd=`cat $lclnam | grep -i radar |awk -v sc=$a -v ct=$ct '{if ($5==sc) print "export RPD_"ct"=10.141.1.xx:y"}'`
			echo $dpd >> file1
			echo $dspd >> file2
                        echo "## Sector "$a "RADAR ">> file1
			echo "## Sector "$a "RADAR ">> file2
			echo $rspd >> file2
			echo $rpd >> file1
			ct=`expr $ct + 1`
                        kaps=$aps
			ft=$ct
		else
                	
			ct=0
       		fi
        done
##                                                                                             ##
##  Get AT spec positions                                                                      ##
##                                                                                             ##
	while test "$ai" -gt 0
        do
		clear
		echo "please enter AT Specilist id (eg w1 s1 ) or blank when complete "
        	read a
        	if test ${#a} -ge 1 
                then
##                                                                                             ##
## Make sure the AT Spec  is valid                                                             ##
##                                                                                             ##
                   ua=`echo $a | tr [:lower:] [:upper:]`
                   a=$ua                                                                            
		   achk=`cat $lclnam | grep -i SPECWS |awk -v sc=$a -v ct=$ct '{if ($4==sc) print $4}'`
                     while test "$achk" = ""
				do
                                   clear 
                                   echo " "
                                   echo "#################    ERROR     ######################################"
                                   echo " "
                                   echo " Vaild AT Specilist Are:"
                                   echo " "
                                   cat $lclnam | grep -i SPECWS | awk '{printf " " $4}'
                                   echo " "
                                   echo " "
				   echo "AT Specilist id not found, please enter AT Specilist id or cntrl-c to exit"
				   read a
				   ua=`echo $a | tr [:lower:] [:upper:]`
                		   a=$ua 
				   achk=`cat $lclnam | grep -i SPECWS |awk -v sc=$a -v ct=$ct '{if ($4==sc) print $4}'`
				done
			ua=`echo $a | tr [:lower:] [:upper:]`
                	a=$ua 
			echo "## ATS Work Station "$a >> file1
			echo "## ATS Work Station "$a >> file2
			ats=`cat $lclnam | grep SPECWS |awk -v sc=$a -v ct=$ai '{if ($4 == sc) print "LPID="$1" DISP=SDS_"ct" APPS=SDS:CMI"};'`
			asts=`cat $lclnam | grep SPECWS |awk -v sc=$a -v ct=$ai '{if ($4 == sc) print "export SDS_"ct"=10.141.1.xx:y"};'`
			echo $ats >> file1 
			echo $asts >> file2
                        ai=`expr $ai + 1`
                        fa=$ai
		else
                	kai=$ai
			ai=0
       		fi
        done
      si=`expr $si + 1 `
  else 
    ft=0 
  echo "   "
  fi
done
rmlcl=$lcl".*.txt"
rm $rmlcl

mv file1 $fnam
mv file2 $dnam
clear
elcl=$asite"_"$lcl

mcnt=`expr ${#asite[@]} - 1`
cflnam=$mcnt"site.run"
##                                                                                             ##
##  Build the .run file                                                                        ##
##                                                                                             ##

cmd="cp /dssc/eopd/fms/ztv/configs/MASTER_FILES/$cflnam $rnam"

$cmd


while test "$mcnt" -eq 1
do        
	sed -e "s/fff/${asite[0]}/g" $rnam > t3
        cp t3 $rnam
	sed -e "s/FFF/${ausite[0]}/g" $rnam > t3
        cp t3 $rnam 
        mcnt=0
done
while test "$mcnt" -eq 2
do
	sed -e "s/fff/${asite[0]}/g" $rnam > t3
        cp t3 $rnam
	sed -e "s/FFF/${ausite[0]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/ggg/${asite[1]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/GGG/${ausite[1]}/g" $rnam > t3
	cp t3 $rnam 
	mcnt=0
done
while test "$mcnt" -eq 3
do
	sed -e "s/fff/${asite[0]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/FFF/${ausite[0]}/g" $rnam > t3	
	cp t3 $rnam
	sed -e "s/ggg/${asite[1]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/GGG/${ausite[1]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/hhh/${asite[2]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/HHH/${ausite[2]}/g" $rnam > t3
	cp t3 $rnam
	mcnt=0
done
while test "$mcnt" -eq 4
do
	sed -e "s/fff/${asite[0]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/FFF/${ausite[0]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/ggg/${asite[1]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/GGG/${ausite[1]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/hhh/${asite[2]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/HHH/${ausite[2]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/jjj/${asite[3]}/g" $rnam > t3
	cp t3 $rnam
	sed -e "s/JJJ/${ausite[3]}/g" $rnam > t3
	cp t3 $rnam
	mcnt=0
done
sed -e "s/run_name/${elcl}/g" $rnam > t3
cp t3 $rnam
cat $rnam |awk -v sc=$fnam -v ct=$PWD '{if (substr($1,1,3) == "CON") print "CONFIG="ct"/"sc; else print $0};' > t3
cp t3 $rnam 
rm t3
