#!/bin/sh
print "\n"
hostname
print "\n"
date
echo "-----------------"
echo "User                     Slots Used                 Running since: \n"
for p in $( ps -ef|grep slot|grep -v "grep"|awk '{print $1}'|sort -u)
do
if [[ -n $(ps -ef|grep $p|grep slot |grep -v "grep"|awk '{print $5}'|sort -n|head -1|grep ":") ]]
then
Start_Time=$(ps -ef|grep $p|grep slot |grep -v "grep"|awk '{print $5}'|sort -n|head -1)
else
Start_Time=$(ps -ef|grep $p|grep slot |grep -v "grep"|awk '{print $5,$6}'|sort -n|head -1)
fi
No_slot=$(ps -ef|grep $p|grep slot |grep -v "grep"|wc -l)
echo "$p                     $No_slot                      $Start_Time  \n"
done

echo "Total slots being used: \n"
echo "$(ps -ef|grep slot|grep -v "grep"|wc -l)\n"

